# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=2, null=True)),
                ('icao', models.CharField(max_length=4, null=True)),
                ('name_uk', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ru', models.CharField(max_length=100, unique=True)),
                ('comments', models.CharField(blank=True, default='', max_length=100)),
                ('auth_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group')),
            ],
            options={
                'db_table': 'airline',
            },
        ),
        migrations.CreateModel(
            name='FlightTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=15)),
                ('airport_from', models.CharField(max_length=4)),
                ('airport_to', models.CharField(max_length=4)),
                ('alt_airport', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_time', models.TimeField()),
                ('flight_duration', models.TimeField()),
                ('firs', models.CharField(blank=True, max_length=100, null=True)),
                ('level450', models.BooleanField(default=False)),
                ('level410', models.BooleanField(default=False)),
                ('level390', models.BooleanField(default=False)),
                ('level340', models.BooleanField(default=False)),
                ('level300', models.BooleanField(default=False)),
                ('level240', models.BooleanField(default=False)),
                ('level180', models.BooleanField(default=False)),
                ('level140', models.BooleanField(default=False)),
                ('level100', models.BooleanField(default=False)),
                ('level050', models.BooleanField(default=False)),
                ('region_c', models.BooleanField(default=False)),
                ('region_g', models.BooleanField(default=False)),
                ('region_h', models.BooleanField(default=False)),
                ('region_eur', models.BooleanField(default=False)),
                ('region_mid', models.BooleanField(default=False)),
                ('region_sasia', models.BooleanField(default=False)),
                ('airmet', models.BooleanField(default=False)),
                ('gamet', models.BooleanField(default=False)),
                ('volcanic_ash', models.BooleanField(default=False)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mbr.Airline')),
            ],
            options={
                'db_table': 'flight_table',
            },
        ),
    ]
