# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbr', '0002_auto_20161225_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='airline',
            name='iata',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='icao',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
