# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbr', '0003_auto_20161228_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flighttable',
            name='flight_id',
        ),
    ]
