# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbr', '0004_remove_flighttable_flight_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airline',
            options={'permissions': (('can_view_mbr_info', 'can get mbr info in html format'),)},
        ),
    ]
